name: Trigger auto deployment for car-game-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/car-game-api-AutoDeployTrigger-92b0b5fe-fca6-4e0c-9ed2-871c2056df2b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CARGAMEAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CARGAMEAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CARGAMEAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.CARGAMEAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CARGAMEAPI_REGISTRY_PASSWORD }}
          containerAppName: car-game-api
          resourceGroup: workshop-rg
          imageToBuild: noriegadocker/car-game-api:latest
          _buildArgumentsKey_: |
            _buildArgumentsValues_


